### ISSUE TITLE
Fix footer styling 

### ISSUE THREAD

**Issue by zurda** [zurda/github-user-finder#13]
See image 
<img width="401" alt="screenshot 2018-10-30 at 18 47 53" src="https://user-images.githubusercontent.com/16784959/47742352-5da1c500-dc74-11e8-93b6-4fad881da0c9.png">

**Comment by kndarp** [comment]
Hi! I'd like to help with this

**Comment by zurda** [comment]
I'd love that, thanks for contributing, @kndarp !
