### ISSUE TITLE
If the search returns 404 -> it isn't possible to create another search 

### ISSUE THREAD

**Issue by zurda** [zurda/github-user-finder#14]
To reproduce: 
1. search for user `msekrgmslermg`
2. observe error in console: 
<img width="679" alt="screenshot 2018-10-30 at 18 55 47" src="https://user-images.githubusercontent.com/16784959/47742886-8d050180-dc75-11e8-86f7-ee7adc4942c6.png">
3. Search for a real user, for example `twitter`

**Comment by kndarp** [comment]
Looking into this

**Comment by zurda** [comment]
I have time tomorrow evening, so I plan to go deeper into this. Hopefully will have some insights tomorrow :)

**Comment by zurda** [comment]
Thanks for the help, @kndarp , feel free to suggest other issues <3
