### ISSUE TITLE
Improve mobile display 

### ISSUE THREAD

**Issue by zurda** [zurda/github-user-finder#3]
There are a lot of issues on mobile, for starters: 

- avatar should be smaller 
- radio buttons should be easier to click

**Comment by EricSnell** [comment]
Hey zurda,
If no one has started to work on these issues I'd be happy to go at it!

**Comment by zurda** [comment]
Hi @EricSnell , I was thinking of starting this today unless you already have. Let me know!

**Comment by EricSnell** [comment]
Hi Michal - all yours!
